os:
    - linx

language: python

python:
    - 3.6.7
    - 3.5.6
    - 3.6.6
    - 3.6.5
    - 3.4.8
    - 3.5.5
    - 3.6.4
    - 3.6.3
    - 3.4.7
    - 3.5.4
    - 3.6.2
    - 3.6.1
    - 3.4.6
    - 3.5.3
    - 3.6.0
    - 3.4.5
    - 3.5.2
    - 3.4.4
    - 3.5.1
    - 3.5.0
    - 3.4.3
    - 3.4.2
    - 3.3.6
    - 3.2.6
    - 3.4.1
    - 3.3.5
    - 3.3.3


install:
    pip install pyvcf

script:
    python ./unittest/test_snpFilter.py
    #echo "Unit testing snpCompare.py"
    python ./unittest/test_snpCompare.py

notifications:
    email: true
