os:
    - linx
    - osx

language: python

python:
    - 3.4.5
    - 3.5.5
    - 3.6.1
    - 3.6.2
    - 3.6.3
    - 3.6.6
    - 3.6.8

install:
    pip install pyvcf

script:
    python ./unittest/test_snpFilter.py
    #echo "Unit testing snpCompare.py"
    #./unittest/test_snpCompare.py

notifications:
    email: true
